version: '3.8'

services:
  db:
    image: postgres:16.1
    container_name: vmag_db
    environment:
      - POSTGRES_DB=vmag
      - POSTGRES_USER=vmag_admin
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: vmag_redis
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: vmag_redis_commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  web:
    build: .
    container_name: vmag_app
    command: >
      sh -c "python manage.py migrate &&
             echo \"from django.contrib.auth import get_user_model; User = get_user_model(); \
             User.objects.filter(username='admin').exists() or \
             User.objects.create_superuser('admin', 'admin@example.com', 'admin')\" | python manage.py shell &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=vmag
      - DB_USERNAME=vmag_admin
      - DB_PASSWORD=admin
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
    depends_on:
      - db
      - redis

volumes:
  postgres_data: